### ISSUE TITLE
Migrate to G2EngineFlags

### ISSUE THREAD

**Issue by docktermj** [Senzing/g2export#24]
In an upcoming version, flags that were reference as G2Engine.FLAGNAME are now referenced as G2EngineFlags.FLAGNAME (as `enum`).  Code needs to be changed to use the new flag style.

A list of flags and "where used" in the code can be found at 
https://github.com/Senzing/knowledge-base/blob/master/lists/where-used-g2-engine-flags.md

Also: https://github.com/Senzing/resolver/issues/74

**Comment by jaeadams** [comment]
I have done the work for this in the version 3.0 preparation branches.  Closing this as complete.
